name: Build and Deploy Static Website

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Build and Deploy
      run: |
        # 在这里添加构建静态网页的命令和脚本
        # 例如，使用静态网站生成器构建网页
        
        # 将构建好的静态文件部署到 GitHub Pages 或其他托管平台
        # 例如，使用 GitHub Pages Action 部署到 GitHub Pages
        
        # 如果您需要添加其他步骤，可以在这里继续添加
    
    - name: Commit and Push Changes
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git add .
        git commit -m "Auto-build and deploy"
        git push
